[package]
name = "java"
version = "0.1.0"
authors = ["Michael Chow <mickey_zhouyou@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.3"
lazy_static = "1.4.0"
