use super::*;
use crate::rtda::*;
use std::fmt::Formatter;
use std::error::Error;

include!("add/dadd.rs");
include!("div/ddiv.rs");
include!("mul/dmul.rs");
include!("neg/dneg.rs");
include!("rem/drem.rs");
include!("sub/dsub.rs");
include!("add/fadd.rs");
include!("div/fdiv.rs");
include!("mul/fmul.rs");
include!("neg/fneg.rs");
include!("rem/frem.rs");
include!("sub/fsub.rs");
include!("add/iadd.rs");
include!("and/iand.rs");
include!("div/idiv.rs");
include!("iinc/iinc.rs");
include!("mul/imul.rs");
include!("neg/ineg.rs");
include!("or/ior.rs");
include!("rem/irem.rs");
include!("sh/ishl.rs");
include!("sh/ishr.rs");
include!("sub/isub.rs");
include!("sh/iushr.rs");
include!("xor/ixor.rs");
include!("add/ladd.rs");
include!("and/land.rs");
include!("div/ldiv.rs");
include!("mul/lmul.rs");
include!("neg/lneg.rs");
include!("or/lor.rs");
include!("rem/lrem.rs");
include!("sh/lshl.rs");
include!("sh/lshr.rs");
include!("sub/lsub.rs");
include!("sh/lushr.rs");
include!("xor/lxor.rs");
