pub trait Instruction {
    fn fetch_operands(&mut self, _reader: &mut BytecodeReader) {
        // nothing to do
    }
    fn execute(&mut self, frame: &mut Frame);
}

enum Inst {
    NOP(NOP),
    ACONST_NULL(ACONST_NULL),
    ICONST_M1(ICONST_M1),
    ICONST_0(ICONST_0),
    ICONST_1(ICONST_1),
    ICONST_2(ICONST_2),
    ICONST_3(ICONST_3),
    ICONST_4(ICONST_4),
    ICONST_5(ICONST_5),
    LCONST_0(LCONST_0),
    LCONST_1(LCONST_1),
    FCONST_0(FCONST_0),
    FCONST_1(FCONST_1),
    FCONST_2(FCONST_2),
    DCONST_0(DCONST_0),
    DCONST_1(DCONST_1),
    BIPUSH(BIPUSH),
    SIPUSH(SIPUSH),
    LDC(LDC),
    LDC_W(LDC_W),
    LDC2_W(LDC2_W),
    ILOAD(ILOAD),
    LLOAD(LLOAD),
    FLOAD(FLOAD),
    DLOAD(DLOAD),
    ALOAD(ALOAD),
    ILOAD_0(ILOAD_0),
    ILOAD_1(ILOAD_1),
    ILOAD_2(ILOAD_2),
    ILOAD_3(ILOAD_3),
    LLOAD_0(LLOAD_0),
    LLOAD_1(LLOAD_1),
    LLOAD_2(LLOAD_2),
    LLOAD_3(LLOAD_3),
    FLOAD_0(FLOAD_0),
    FLOAD_1(FLOAD_1),
    FLOAD_2(FLOAD_2),
    FLOAD_3(FLOAD_3),
    DLOAD_0(DLOAD_0),
    DLOAD_1(DLOAD_1),
    DLOAD_2(DLOAD_2),
    DLOAD_3(DLOAD_3),
    ALOAD_0(ALOAD_0),
    ALOAD_1(ALOAD_1),
    ALOAD_2(ALOAD_2),
    ALOAD_3(ALOAD_3),
    IALOAD(IALOAD),
    LALOAD(LALOAD),
    FALOAD(FALOAD),
    DALOAD(DALOAD),
    AALOAD(AALOAD),
    BALOAD(BALOAD),
    CALOAD(CALOAD),
    SALOAD(SALOAD),
    ISTORE(ISTORE),
    LSTORE(LSTORE),
    FSTORE(FSTORE),
    DSTORE(DSTORE),
    ASTORE(ASTORE),
    ISTORE_0(ISTORE_0),
    ISTORE_1(ISTORE_1),
    ISTORE_2(ISTORE_2),
    ISTORE_3(ISTORE_3),
    LSTORE_0(LSTORE_0),
    LSTORE_1(LSTORE_1),
    LSTORE_2(LSTORE_2),
    LSTORE_3(LSTORE_3),
    FSTORE_0(FSTORE_0),
    FSTORE_1(FSTORE_1),
    FSTORE_2(FSTORE_2),
    FSTORE_3(FSTORE_3),
    DSTORE_0(DSTORE_0),
    DSTORE_1(DSTORE_1),
    DSTORE_2(DSTORE_2),
    DSTORE_3(DSTORE_3),
    ASTORE_0(ASTORE_0),
    ASTORE_1(ASTORE_1),
    ASTORE_2(ASTORE_2),
    ASTORE_3(ASTORE_3),
    IASTORE(IASTORE),
    LASTORE(LASTORE),
    FASTORE(FASTORE),
    DASTORE(DASTORE),
    AASTORE(AASTORE),
    BASTORE(BASTORE),
    CASTORE(CASTORE),
    SASTORE(SASTORE),
    POP(POP),
    POP2(POP2),
    DUP(DUP),
    DUP_X1(DUP_X1),
    DUP_X2(DUP_X2),
    DUP2(DUP2),
    DUP2_X1(DUP2_X1),
    DUP2_X2(DUP2_X2),
    SWAP(SWAP),
    IADD(IADD),
    LADD(LADD),
    FADD(FADD),
    DADD(DADD),
    ISUB(ISUB),
    LSUB(LSUB),
    FSUB(FSUB),
    DSUB(DSUB),
    IMUL(IMUL),
    LMUL(LMUL),
    FMUL(FMUL),
    DMUL(DMUL),
    IDIV(IDIV),
    LDIV(LDIV),
    FDIV(FDIV),
    DDIV(DDIV),
    IREM(IREM),
    LREM(LREM),
    FREM(FREM),
    DREM(DREM),
    INEG(INEG),
    LNEG(LNEG),
    FNEG(FNEG),
    DNEG(DNEG),
    ISHL(ISHL),
    LSHL(LSHL),
    ISHR(ISHR),
    LSHR(LSHR),
    IUSHR(IUSHR),
    LUSHR(LUSHR),
    IAND(IAND),
    LAND(LAND),
    IOR(IOR),
    LOR(LOR),
    IXOR(IXOR),
    LXOR(LXOR),
    IINC(IINC),
    I2L(I2L),
    I2F(I2F),
    I2D(I2D),
    L2I(L2I),
    L2F(L2F),
    L2D(L2D),
    F2I(F2I),
    F2L(F2L),
    F2D(F2D),
    D2I(D2I),
    D2L(D2L),
    D2F(D2F),
    I2B(I2B),
    I2C(I2C),
    I2S(I2S),
    LCMP(LCMP),
    FCMPL(FCMPL),
    FCMPG(FCMPG),
    DCMPL(DCMPL),
    DCMPG(DCMPG),
    IFEQ(IFEQ),
    IFNE(IFNE),
    IFLT(IFLT),
    IFGE(IFGE),
    IFGT(IFGT),
    IFLE(IFLE),
    IF_ICMPEQ(IF_ICMPEQ),
    IF_ICMPNE(IF_ICMPNE),
    IF_ICMPLT(IF_ICMPLT),
    IF_ICMPGE(IF_ICMPGE),
    IF_ICMPGT(IF_ICMPGT),
    IF_ICMPLE(IF_ICMPLE),
    IF_ACMPEQ(IF_ACMPEQ),
    IF_ACMPNE(IF_ACMPNE),
    GOTO(GOTO),
    JSR(JSR),
    RET(RET),
    TABLE_SWITCH(TABLE_SWITCH),
    LOOKUP_SWITCH(LOOKUP_SWITCH),
    I_RETURN(I_RETURN),
    L_RETURN(L_RETURN),
    F_RETURN(F_RETURN),
    D_RETURN(D_RETURN),
    A_RETURN(A_RETURN),
    RETURN(RETURN),
    GET_STATIC(GET_STATIC),
    PUT_STATIC(PUT_STATIC),
    GET_FIELD(GET_FIELD),
    PUT_FIELD(PUT_FIELD),
    INVOKE_VIRTUAL(INVOKE_VIRTUAL),
    INVOKE_SPECIAL(INVOKE_SPECIAL),
    INVOKE_STATIC(INVOKE_STATIC),
    INVOKE_INTERFACE(INVOKE_INTERFACE),
    INVOKE_DYNAMIC(INVOKE_DYNAMIC),
    NEW(NEW),
    NEW_ARRAY(NEW_ARRAY),
    ANEW_ARRAY(ANEW_ARRAY),
    ARRAY_LENGTH(ARRAY_LENGTH),
    ATHROW(ATHROW),
    CHECK_CAST(CHECK_CAST),
    INSTANCE_OF(INSTANCE_OF),
    MONITOR_ENTER(MONITOR_ENTER),
    MONITOR_EXIT(MONITOR_EXIT),
    WIDE(WIDE),
    MULTI_ANEW_ARRAY(MULTI_ANEW_ARRAY),
    IFNULL(IFNULL),
    IFNONNULL(IFNONNULL),
    GOTO_W(GOTO_W),
    JSR_W(JSR_W),
    BREAK_POINT(BREAK_POINT),
    IMPDEP1(IMPDEP1),
    IMPDEP2(IMPDEP2),
}

pub fn new_Instruction(opcode: u8) -> Inst {
    match opcode {
        00 => Inst::NOP(NOP {}),
        01 => Inst::ACONST_NULL(ACONST_NULL {}),
        02 => Inst::ICONST_M1(ICONST_M1 {}),
        03 => Inst::ICONST_0(ICONST_0 {}),
        04 => Inst::ICONST_1(ICONST_1 {}),
        05 => Inst::ICONST_2(ICONST_2 {}),
        06 => Inst::ICONST_3(ICONST_3 {}),
        07 => Inst::ICONST_4(ICONST_4 {}),
        08 => Inst::ICONST_5(ICONST_5 {}),
        09 => Inst::LCONST_0(LCONST_0 {}),
        10 => Inst::LCONST_1(LCONST_1 {}),
        11 => Inst::FCONST_0(FCONST_0 {}),
        12 => Inst::FCONST_1(FCONST_1 {}),
        13 => Inst::FCONST_2(FCONST_2 {}),
        14 => Inst::DCONST_0(DCONST_0 {}),
        15 => Inst::DCONST_1(DCONST_1 {}),
        16 => Inst::BIPUSH(BIPUSH::new()),
        17 => Inst::SIPUSH(SIPUSH::new()),
        18 => Inst::LDC(LDC {}),
        19 => Inst::LDC_W(LDC_W {}),
        20 => Inst::LDC2_W(LDC2_W {}),
        21 => Inst::ILOAD(ILOAD::new(0)),
        22 => Inst::LLOAD(LLOAD::new(0)),
        23 => Inst::FLOAD(FLOAD::new(0)),
        24 => Inst::DLOAD(DLOAD::new(0)),
        25 => Inst::ALOAD(ALOAD::new(0)),
        26 => Inst::ILOAD_0(ILOAD_0 {}),
        27 => Inst::ILOAD_1(ILOAD_1 {}),
        28 => Inst::ILOAD_2(ILOAD_2 {}),
        29 => Inst::ILOAD_3(ILOAD_3 {}),
        30 => Inst::LLOAD_0(LLOAD_0 {}),
        31 => Inst::LLOAD_1(LLOAD_1 {}),
        32 => Inst::LLOAD_2(LLOAD_2 {}),
        33 => Inst::LLOAD_3(LLOAD_3 {}),
        34 => Inst::FLOAD_0(FLOAD_0 {}),
        35 => Inst::FLOAD_1(FLOAD_1 {}),
        36 => Inst::FLOAD_2(FLOAD_2 {}),
        37 => Inst::FLOAD_3(FLOAD_3 {}),
        38 => Inst::DLOAD_0(DLOAD_0 {}),
        39 => Inst::DLOAD_1(DLOAD_1 {}),
        40 => Inst::DLOAD_2(DLOAD_2 {}),
        41 => Inst::DLOAD_3(DLOAD_3 {}),
        42 => Inst::ALOAD_0(ALOAD_0 {}),
        43 => Inst::ALOAD_1(ALOAD_1 {}),
        44 => Inst::ALOAD_2(ALOAD_2 {}),
        45 => Inst::ALOAD_3(ALOAD_3 {}),
        46 => Inst::IALOAD(IALOAD {}),
        47 => Inst::LALOAD(LALOAD {}),
        48 => Inst::FALOAD(FALOAD {}),
        49 => Inst::DALOAD(DALOAD {}),
        50 => Inst::AALOAD(AALOAD {}),
        51 => Inst::BALOAD(BALOAD {}),
        52 => Inst::CALOAD(CALOAD {}),
        53 => Inst::SALOAD(SALOAD {}),
        54 => Inst::ISTORE(ISTORE::new(0)),
        55 => Inst::LSTORE(LSTORE::new(0)),
        56 => Inst::FSTORE(FSTORE::new(0)),
        57 => Inst::DSTORE(DSTORE::new(0)),
        58 => Inst::ASTORE(ASTORE::new(0)),
        59 => Inst::ISTORE_0(ISTORE_0 {}),
        60 => Inst::ISTORE_1(ISTORE_1 {}),
        61 => Inst::ISTORE_2(ISTORE_2 {}),
        62 => Inst::ISTORE_3(ISTORE_3 {}),
        63 => Inst::LSTORE_0(LSTORE_0 {}),
        64 => Inst::LSTORE_1(LSTORE_1 {}),
        65 => Inst::LSTORE_2(LSTORE_2 {}),
        66 => Inst::LSTORE_3(LSTORE_3 {}),
        67 => Inst::FSTORE_0(FSTORE_0 {}),
        68 => Inst::FSTORE_1(FSTORE_1 {}),
        69 => Inst::FSTORE_2(FSTORE_2 {}),
        70 => Inst::FSTORE_3(FSTORE_3 {}),
        71 => Inst::DSTORE_0(DSTORE_0 {}),
        72 => Inst::DSTORE_1(DSTORE_1 {}),
        73 => Inst::DSTORE_2(DSTORE_2 {}),
        74 => Inst::DSTORE_3(DSTORE_3 {}),
        75 => Inst::ASTORE_0(ASTORE_0 {}),
        76 => Inst::ASTORE_1(ASTORE_1 {}),
        77 => Inst::ASTORE_2(ASTORE_2 {}),
        78 => Inst::ASTORE_3(ASTORE_3 {}),
        79 => Inst::IASTORE(IASTORE {}),
        80 => Inst::LASTORE(LASTORE {}),
        81 => Inst::FASTORE(FASTORE {}),
        82 => Inst::DASTORE(DASTORE {}),
        83 => Inst::AASTORE(AASTORE {}),
        84 => Inst::BASTORE(BASTORE {}),
        85 => Inst::CASTORE(CASTORE {}),
        86 => Inst::SASTORE(SASTORE {}),
        87 => Inst::POP(POP {}),
        88 => Inst::POP2(POP2 {}),
        89 => Inst::DUP(DUP {}),
        90 => Inst::DUP_X1(DUP_X1 {}),
        91 => Inst::DUP_X2(DUP_X2 {}),
        92 => Inst::DUP2(DUP2 {}),
        93 => Inst::DUP2_X1(DUP2_X1 {}),
        94 => Inst::DUP2_X2(DUP2_X2 {}),
        95 => Inst::SWAP(SWAP {}),
        96 => Inst::IADD(IADD {}),
        97 => Inst::LADD(LADD {}),
        98 => Inst::FADD(FADD {}),
        99 => Inst::DADD(DADD {}),
        100 => Inst::ISUB(ISUB {}),
        101 => Inst::LSUB(LSUB {}),
        102 => Inst::FSUB(FSUB {}),
        103 => Inst::DSUB(DSUB {}),
        104 => Inst::IMUL(IMUL {}),
        105 => Inst::LMUL(LMUL {}),
        106 => Inst::FMUL(FMUL {}),
        107 => Inst::DMUL(DMUL {}),
        108 => Inst::IDIV(IDIV {}),
        109 => Inst::LDIV(LDIV {}),
        110 => Inst::FDIV(FDIV {}),
        111 => Inst::DDIV(DDIV {}),
        112 => Inst::IREM(IREM {}),
        113 => Inst::LREM(LREM {}),
        114 => Inst::FREM(FREM {}),
        115 => Inst::DREM(DREM {}),
        116 => Inst::INEG(INEG {}),
        117 => Inst::LNEG(LNEG {}),
        118 => Inst::FNEG(FNEG {}),
        119 => Inst::DNEG(DNEG {}),
        120 => Inst::ISHL(ISHL {}),
        121 => Inst::LSHL(LSHL {}),
        122 => Inst::ISHR(ISHR {}),
        123 => Inst::LSHR(LSHR {}),
        124 => Inst::IUSHR(IUSHR {}),
        125 => Inst::LUSHR(LUSHR {}),
        126 => Inst::IAND(IAND {}),
        127 => Inst::LAND(LAND {}),
        128 => Inst::IOR(IOR {}),
        129 => Inst::LOR(LOR {}),
        130 => Inst::IXOR(IXOR {}),
        131 => Inst::LXOR(LXOR {}),
        132 => Inst::IINC(IINC::new(0, 0)),
        133 => Inst::I2L(I2L {}),
        134 => Inst::I2F(I2F {}),
        135 => Inst::I2D(I2D {}),
        136 => Inst::L2I(L2I {}),
        137 => Inst::L2F(L2F {}),
        138 => Inst::L2D(L2D {}),
        139 => Inst::F2I(F2I {}),
        140 => Inst::F2L(F2L {}),
        141 => Inst::F2D(F2D {}),
        142 => Inst::D2I(D2I {}),
        143 => Inst::D2L(D2L {}),
        144 => Inst::D2F(D2F {}),
        145 => Inst::I2B(I2B {}),
        146 => Inst::I2C(I2C {}),
        147 => Inst::I2S(I2S {}),
        148 => Inst::LCMP(LCMP {}),
        149 => Inst::FCMPL(FCMPL {}),
        150 => Inst::FCMPG(FCMPG {}),
        151 => Inst::DCMPL(DCMPL {}),
        152 => Inst::DCMPG(DCMPG {}),
        153 => Inst::IFEQ(IFEQ::new()),
        154 => Inst::IFNE(IFNE::new()),
        155 => Inst::IFLT(IFLT::new()),
        156 => Inst::IFGE(IFGE::new()),
        157 => Inst::IFGT(IFGT::new()),
        158 => Inst::IFLE(IFLE::new()),
        159 => Inst::IF_ICMPEQ(IF_ICMPEQ::new()),
        160 => Inst::IF_ICMPNE(IF_ICMPNE::new()),
        161 => Inst::IF_ICMPLT(IF_ICMPLT::new()),
        162 => Inst::IF_ICMPGE(IF_ICMPGE::new()),
        163 => Inst::IF_ICMPGT(IF_ICMPGT::new()),
        164 => Inst::IF_ICMPLE(IF_ICMPLE::new()),
        165 => Inst::IF_ACMPEQ(IF_ACMPEQ::new()),
        166 => Inst::IF_ACMPNE(IF_ACMPNE::new()),
        167 => Inst::GOTO(GOTO::new()),
        168 => Inst::JSR(JSR {}),
        169 => Inst::RET(RET {}),
        170 => Inst::TABLE_SWITCH(TABLE_SWITCH::new()),
        171 => Inst::LOOKUP_SWITCH(LOOKUP_SWITCH::new()),
        172 => Inst::I_RETURN(I_RETURN {}),
        173 => Inst::L_RETURN(L_RETURN {}),
        174 => Inst::F_RETURN(F_RETURN {}),
        175 => Inst::D_RETURN(D_RETURN {}),
        176 => Inst::A_RETURN(A_RETURN {}),
        177 => Inst::RETURN(RETURN {}),
        178 => Inst::GET_STATIC(GET_STATIC {}),
        179 => Inst::PUT_STATIC(PUT_STATIC {}),
        180 => Inst::GET_FIELD(GET_FIELD {}),
        181 => Inst::PUT_FIELD(PUT_FIELD {}),
        182 => Inst::INVOKE_VIRTUAL(INVOKE_VIRTUAL {}),
        183 => Inst::INVOKE_SPECIAL(INVOKE_SPECIAL {}),
        184 => Inst::INVOKE_STATIC(INVOKE_STATIC {}),
        185 => Inst::INVOKE_INTERFACE(INVOKE_INTERFACE {}),
        186 => Inst::INVOKE_DYNAMIC(INVOKE_DYNAMIC {}),
        187 => Inst::NEW(NEW {}),
        188 => Inst::NEW_ARRAY(NEW_ARRAY {}),
        189 => Inst::ANEW_ARRAY(ANEW_ARRAY {}),
        190 => Inst::ARRAY_LENGTH(ARRAY_LENGTH {}),
        191 => Inst::ATHROW(ATHROW {}),
        192 => Inst::CHECK_CAST(CHECK_CAST {}),
        193 => Inst::INSTANCE_OF(INSTANCE_OF {}),
        194 => Inst::MONITOR_ENTER(MONITOR_ENTER {}),
        195 => Inst::MONITOR_EXIT(MONITOR_EXIT {}),
        196 => Inst::WIDE(WIDE::new()),
        197 => Inst::MULTI_ANEW_ARRAY(MULTI_ANEW_ARRAY {}),
        198 => Inst::IFNULL(IFNULL::new()),
        199 => Inst::IFNONNULL(IFNONNULL::new()),
        200 => Inst::GOTO_W(GOTO_W::new()),
        201 => Inst::JSR_W(JSR_W {}),
        202 => Inst::BREAK_POINT(BREAK_POINT {}),
        254 => Inst::IMPDEP1(IMPDEP1 {}),
        255 => Inst::IMPDEP2(IMPDEP2 {}),
        _ => panic!("Unsupported opcode: {}!", opcode),
    }
}