use super::*;
use std::fmt::Formatter;
use std::fmt::Error;

include!("aaload.rs");
include!("aload.rs");
include!("aload_0.rs");
include!("aload_1.rs");
include!("aload_2.rs");
include!("aload_3.rs");
include!("baload.rs");
include!("caload.rs");
include!("daload.rs");
include!("dload.rs");
include!("dload_0.rs");
include!("dload_1.rs");
include!("dload_2.rs");
include!("dload_3.rs");
include!("faload.rs");
include!("fload.rs");
include!("fload_0.rs");
include!("fload_1.rs");
include!("fload_2.rs");
include!("fload_3.rs");
include!("iaload.rs");
include!("iload.rs");
include!("iload_0.rs");
include!("iload_1.rs");
include!("iload_2.rs");
include!("iload_3.rs");
include!("laload.rs");
include!("lload.rs");
include!("lload_0.rs");
include!("lload_1.rs");
include!("lload_2.rs");
include!("lload_3.rs");
include!("saload.rs");